/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RendezVousRouteImport } from './routes/rendez-vous'
import { Route as PersonnelRouteImport } from './routes/personnel'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MedicamentsRouteImport } from './routes/medicaments'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BedsRouteImport } from './routes/beds'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientsNewRouteImport } from './routes/patients/new'
import { Route as PatientsPatientIdRouteImport } from './routes/patients/$patientId'

const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RendezVousRoute = RendezVousRouteImport.update({
  id: '/rendez-vous',
  path: '/rendez-vous',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonnelRoute = PersonnelRouteImport.update({
  id: '/personnel',
  path: '/personnel',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicamentsRoute = MedicamentsRouteImport.update({
  id: '/medicaments',
  path: '/medicaments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BedsRoute = BedsRouteImport.update({
  id: '/beds',
  path: '/beds',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsNewRoute = PatientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/beds': typeof BedsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/medicaments': typeof MedicamentsRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/personnel': typeof PersonnelRoute
  '/rendez-vous': typeof RendezVousRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/tarifs': typeof TarifsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/beds': typeof BedsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/medicaments': typeof MedicamentsRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/personnel': typeof PersonnelRoute
  '/rendez-vous': typeof RendezVousRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/tarifs': typeof TarifsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/beds': typeof BedsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/medicaments': typeof MedicamentsRoute
  '/notifications': typeof NotificationsRoute
  '/patients': typeof PatientsRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/personnel': typeof PersonnelRoute
  '/rendez-vous': typeof RendezVousRoute
  '/services': typeof ServicesRoute
  '/set-password': typeof SetPasswordRoute
  '/tarifs': typeof TarifsRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/patients/new': typeof PatientsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/beds'
    | '/contact'
    | '/dashboard'
    | '/medicaments'
    | '/notifications'
    | '/patients'
    | '/payments'
    | '/personnel'
    | '/rendez-vous'
    | '/services'
    | '/set-password'
    | '/tarifs'
    | '/patients/$patientId'
    | '/patients/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/beds'
    | '/contact'
    | '/dashboard'
    | '/medicaments'
    | '/notifications'
    | '/patients'
    | '/payments'
    | '/personnel'
    | '/rendez-vous'
    | '/services'
    | '/set-password'
    | '/tarifs'
    | '/patients/$patientId'
    | '/patients/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/beds'
    | '/contact'
    | '/dashboard'
    | '/medicaments'
    | '/notifications'
    | '/patients'
    | '/payments'
    | '/personnel'
    | '/rendez-vous'
    | '/services'
    | '/set-password'
    | '/tarifs'
    | '/patients/$patientId'
    | '/patients/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BedsRoute: typeof BedsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  MedicamentsRoute: typeof MedicamentsRoute
  NotificationsRoute: typeof NotificationsRoute
  PatientsRoute: typeof PatientsRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  PersonnelRoute: typeof PersonnelRoute
  RendezVousRoute: typeof RendezVousRoute
  ServicesRoute: typeof ServicesRoute
  SetPasswordRoute: typeof SetPasswordRoute
  TarifsRoute: typeof TarifsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rendez-vous': {
      id: '/rendez-vous'
      path: '/rendez-vous'
      fullPath: '/rendez-vous'
      preLoaderRoute: typeof RendezVousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personnel': {
      id: '/personnel'
      path: '/personnel'
      fullPath: '/personnel'
      preLoaderRoute: typeof PersonnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicaments': {
      id: '/medicaments'
      path: '/medicaments'
      fullPath: '/medicaments'
      preLoaderRoute: typeof MedicamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beds': {
      id: '/beds'
      path: '/beds'
      fullPath: '/beds'
      preLoaderRoute: typeof BedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/new': {
      id: '/patients/new'
      path: '/new'
      fullPath: '/patients/new'
      preLoaderRoute: typeof PatientsNewRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
  }
}

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  PatientsNewRoute: typeof PatientsNewRoute
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  PatientsNewRoute: PatientsNewRoute,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BedsRoute: BedsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  MedicamentsRoute: MedicamentsRoute,
  NotificationsRoute: NotificationsRoute,
  PatientsRoute: PatientsRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  PersonnelRoute: PersonnelRoute,
  RendezVousRoute: RendezVousRoute,
  ServicesRoute: ServicesRoute,
  SetPasswordRoute: SetPasswordRoute,
  TarifsRoute: TarifsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
